services:  
  postgres_db_dev:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
    ports:
      - "5432:5432"
  postgres_db_cprod:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${CPROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CPROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CPROD_POSTGRES_DB}
    ports:
      - "2345:5432"