dbt_dev_samples:
  outputs:
    dev:
      dbname: dev_db
      host: localhost
      pass: password
      port: 5432
      schema: not_used
      threads: 1
      type: postgres
      user: postgres
    sample-dev:
      dbname: dev_db
      host: localhost
      pass: password
      port: 5432
      schema: "{{ env_var('DEV_NAME', 'dev') }}"
      threads: 1
      type: postgres
      user: postgres
    cprod:
      dbname: cprod_db
      host: localhost
      pass: password
      port: 2345
      schema: public
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: prod_db
      host: localhost
      pass: password
      port: 1234
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
